#ifndef __DISPIDS_H__
#define __DISPIDS_H__

#define DISPID_ACTIVEBAR 0
#define DISPID_DESIGNERTREE 1
#define DISPID_ATTACHDESIGNERTREE 2
#define DISPID_ATTACHCATEGORYTREE 3
#define DISPID_ALTF10 4
#define DISPID_TRANSLATEACCELERATOR 5
#define DISPID_CREATETOOLBAR 6
#define DISPID_ONCOMMAND 7
#define DISPID_ATTACHBROWSER 8
#define DISPID_REGISTERDROPTARGET 9
#define DISPID_REVOKEDRAGDROP 10
#define DISPID_MDIACTIVEBAR 11
#define DISPID_OPENWINDOW 12
#define DISPID_CLOSEWINDOW 13
#define DISPID_SETFOCUS 14
#define DISPID_ISDIRTY 15
#define DISPID_OPENDESIGNER 16
#define DISPID_CLOSEDESIGNER 17
#define DISPID_UIDEACTIVATECLOSE 18

#endif

