//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by prj.rc
//
#define IDS_LOADPICT                    1
#define IDS_SAVEIMAGE                   2
#define IDS_CAT_NONE                    3
#define IDS_DELETETOOLCONFIRM           5
#define IDS_DELETECATEGORYCONFIRM       6
#define IDS_AUTOCREATEMASKCONFIRM       7
#define IDS_DELETEBANDCONFIRM           8
#define IDS_DELETECHILDBANDCONFIRM      9
#define ID_PAINT_MOVER                  101
#define IDC_COLORWELL                   102
#define IDCC_DRAGTOOLNOT                103
#define IDI_MAINWIN                     103
#define IDC_IMAGEPREVIEW                104
#define IDD_DLG_POPUPS                  104
#define IDM_MAINWIN                     104
#define ID_SETPAGEDIRTY                 105
#define IDD_DLG_OPTIONS                 105
#define IDR_TBDESIGNER                  106
#define IDC_CLRPREVIEW                  107
#define IDB_PAINT_BAR                   108
#define PREFID_DESIGNER                 108
#define IDB_CATEGORY                    109
#define IDD_DESIGNER                    109
#define PREFID_LIBRARY                  109
#define IDB_HIERARCHY                   110
#define PREFID_DESIGNERTRACKER          110
#define IDCC_DRAGTOOLMOVE               111
#define ID_TOOLBAR                      111
#define IDD_LIBRARY                     112
#define PREFID_DESIGNERTRACKER2         112
#define IDB_STATEANDSHIFT               113
#define PREFID_ICONEDITOR               113
#define IDR_TBLIBRARY                   114
#define ID_PLACEHOLDERSPACE             114
#define IDD_NEWCATEGORY                 116
#define IDD_ICONEDITOR                  117
#define IDD_DLG_DEFINECOLOR             118
#define IDR_ACCEL1                      118
#define IDD_BITMAPSCALE                 121
#define IDB_CYCLE                       123
#define IDC_SNAPSHOT                    124
#define IDR_DESIGNER                    125
#define IDD_CONFIRM                     125
#define IDI_ICON_CANCEL                 127
#define IDD_DLG_TOOLS                   128
#define IDD_OPEN_ICONEDITOR             130
#define IDR_MNU_BAND                    131
#define IDR_FILEDEMENSIONS              132
#define IDR_MNGCATE                     133
#define IDC_MENUGRAB                    133
#define IDD_PAGE                        134
#define IDC_MENUGRABNOT                 134
#define IDD_DESIGNER1                   136
#define IDB_SPECHIGH                    137
#define IDB_SPECLOW                     138
#define IDD_DESIGNER3                   139
#define IDD_BAND                        205
#define IDD_TOOL                        206
#define IDB_HATCH                       302
#define IDC_ED_CAPTION                  1001
#define IDC_LST_POPUP                   1001
#define IDC_CHK_BAND                    1002
#define IDC_CHK_PAGE                    1003
#define IDC_CHK_TOOL                    1004
#define IDC_TYPE                        1005
#define IDC_CHK_CATEGORY                1005
#define IDC_ED_NAME                     1006
#define IDC_CHK_AUTOCREATEMASK          1006
#define IDC_TREELIBRARY                 1009
#define IDC_BROWSER                     1010
#define IDC_TOOLBAR                     1011
#define ID_ADDCOLOR                     1013
#define IDC_ED_HUE                      1014
#define IDC_ED_SAT                      1015
#define IDC_ED_LUM                      1016
#define IDC_ED_RED                      1017
#define IDC_ED_GREEN                    1018
#define IDC_ED_BLUE                     1019
#define ID_CLOSE                        1020
#define IDC_LUMINOSITY                  1021
#define IDC_COLORSPECTRUM               1022
#define IDC_STATIC_COLOR                1023
#define IDC_SPIN_HUE                    1024
#define IDC_SPIN_SAT                    1025
#define IDC_EDIT1                       1025
#define IDC_DESIGNERBANDLIMIT           1025
#define IDC_ED_LIBPATH                  1025
#define IDC_SPIN_LUM                    1026
#define IDC_SPIN1                       1026
#define IDC_SPIN_RED                    1027
#define IDC_TREETOOLS                   1027
#define IDC_SPIN_GREEN                  1028
#define IDC_CHK_CREATEMASK              1028
#define IDC_SPIN_BLUE                   1029
#define IDC_PICTURE                     1032
#define IDC_TREE_DESIGNER               1033
#define IDC_STATICTREE                  1034
#define IDAPPLY                         1036
#define ID_HELP2                        1036
#define IDC_LST_PROPERTIES              1037
#define IDC_BN_GETPATH                  1037
#define IDC_CHK_EVENTLOGGING            1040
#define IDC_CHK_SORTBANDS               1041
#define IDC_ST_DESC                     1041
#define IDC_NAME                        1061
#define IDC_OPT_SCALETOTOOL             1067
#define IDC_OPT_CLIPIMAGE               1068
#define IDC_OPT_EQUAL                   1069
#define IDC_DONTSHOW                    1076
#define IDC_MSG                         1077
#define IDS_BANDTYPES                   2000
#define IDS_BANDTYPES1                  2001
#define IDS_BANDTYPES2                  2002
#define IDS_BANDTYPES3                  2003
#define IDS_BANDTYPES4                  2004
#define IDS_ALT                         2010
#define IDS_CONTROL                     2011
#define IDS_SHIFT                       2012
#define IDS_DUPLICATESHORTCUT           2013
#define IDS_ACTIVEBARHELP               2014
#define IDS_ERR_QUERYACTIVEBARINTERFACE 3013
#define IDS_FAILEDTORESTORELAYOUT       3020
#define IDS_EXCEPTION_ACCESS_VIOLATION  4010
#define IDS_EXCEPTION_ARRAY_BOUNDS_EXCEEDED 4011
#define IDS_EXCEPTION_BREAKPOINT        4012
#define IDS_EXCEPTION_DATATYPE_MISALIGNMENT 4013
#define IDS_EXCEPTION_FLT_DENORMAL_OPERAND 4014
#define IDS_EXCEPTION_FLT_DIVIDE_BY_ZERO 4015
#define IDS_EXCEPTION_FLT_INEXACT_RESULT 4016
#define IDS_EXCEPTION_FLT_INVALID_OPERATION 4017
#define IDS_EXCEPTION_FLT_OVERFLOW      4018
#define IDS_EXCEPTION_FLT_STACK_CHECK   4019
#define IDS_EXCEPTION_FLT_UNDERFLOW     4020
#define IDS_EXCEPTION_ILLEGAL_INSTRUCTION 4021
#define IDS_EXCEPTION_IN_PAGE_ERROR     4022
#define IDS_EXCEPTION_INT_DIVIDE_BY_ZERO 4023
#define IDS_EXCEPTION_INT_OVERFLOW      4024
#define IDS_EXCEPTION_INVALID_DISPOSITION 4025
#define IDS_EXCEPTION_NONCONTINUABLE_EXCEPTION 4026
#define IDS_EXCEPTION_PRIV_INSTRUCTION  4027
#define IDS_EXCEPTION_SINGLE_STEP       4028
#define IDS_EXCEPTION_STACK_OVERFLOW    4029
#define IDS_DESIGNER                    4030
#define IDS_DESIGNERDOC                 4031
#define IDS_DESIGNERTITLE               4032
#define IDS_ERR_FAILEDTOGETBANDSOBJECT  10000
#define IDS_ERR_FAILEDTOGETBANDOBJECT   10001
#define IDS_ERR_FAILEDTOGETPAGESOBJECT  10002
#define IDS_ERR_FAILEDTOGETCHILDBANDSOBJECT 10002
#define IDS_ERR_FAILEDTOGETPAGEOBJECT   10003
#define IDS_ERR_FAILEDTOGETCHILDBANDOBJECT 10003
#define IDS_ERR_FAILEDTOGETTOOLS        10004
#define IDS_ERR_FAILEDTOGETTOOL         10005
#define IDS_ERR_FAILEDTOGETACTIVEBAROBJECT 10006
#define IDS_ERR_FAILEDTOINSERTNEWBAND   10010
#define IDS_ERR_FAILEDTOCREATENEWBAND   10010
#define IDS_ERR_FAILEDTOCREATEANEWPAGE  10011
#define IDS_ERR_FAILEDTOCREATEANEWCHILDBAND 10011
#define IDS_ERR_FAILEDTOCREATEANEWTOOL  10012
#define IDS_ERR_FAILEDTOGETBANDCOUNT    10013
#define IDS_ERR_FAILEDTOGETPAGECOUNT    10014
#define IDS_ERR_FAILEDTOGETPAGESCOUNT   10014
#define IDS_ERR_FAILEDTOGETCHILDBANDCOUNT 10014
#define IDS_ERR_FAILEDTOGETTOOLCOUNT    10015
#define IDS_ERR_LOADINGIMAGEFAILED      10021
#define IDS_ERR_IMAGETOOBIG             10022
#define IDS_ERR_COULDNOTCREATEBITMAP    10100
#define IDS_ERR_COULNDNOTCREATEFILE     10101
#define IDS_ERR_COULDNOTCREATEFILE      10102
#define IDS_ERR_COULDNOTSAVEIMAGE       10103
#define IDS_ERR_COULDNOTOPENCLIPBOARD   10104
#define IDS_ERR_COULDNOTOPENCLIPBROAD   10104
#define IDS_ERR_COULDNOTSETCLIPBOARD    10105
#define IDS_ERR_COULDNOTSETCLIPBROAD    10105
#define IDS_ERR_COULDNOTCLOSECLIPBOARD  10106
#define IDS_ERR_COULDNOTCLOSECLIPBROAD  10106
#define IDS_ERR_COULDNOTGETCLIPBOARDDATA 10107
#define IDS_ERR_COULDNOTGETCLIPBROADDATA 10107
#define IDS_ERR_COULDNOTCREATEIPICTURE  10108
#define IDS_ERR_FAILEDTOCREATETHETOOLDATAOBJECT 10109
#define IDS_ERR_FAILEDTOOPENFILE        10200
#define IDS_ERR_FAILEDTOCREATEASTREAM   10201
#define IDS_ERR_FAILEDTOSAVELAYOUT      10202
#define IDS_ERR_FAILEDTOLOADLAYOUT      10203
#define IDS_ERR_FAILEDTOSETBANDTYPE     10204
#define IDS_ERR_FAILEDTOGETTHETOOLOBJECT 10205
#define IDS_ERR_FAILEDTODELETETOOL      10206
#define IDS_ERR_FAILEDTOGETTOOLGATEGORY 10207
#define IDS_ERR_FAILEDTODELETECATEGORY  10208
#define IDS_ERR_FAILEDTOCREATECATEGORY  10209
#define IDS_ERR_MENULOADFAILED          10210
#define IDS_ERR_FAILEDTOGETSUBMENU      10211
#define IDS_ERR_TRACKPOPUPFAILED        10212
#define IDS_ERR_FAILEDTOINSERTTREEITEM  10213
#define IDS_ERR_FAILEDTOSETTHETOOLSCAPTION 10214
#define IDS_ERR_FAILEDTOCREATEDESIGNER  10215
#define IDS_ERR_COULDNOTGETPARENTTREEITEM 10216
#define IDS_ERR_FAILEDTOSETLAYOUT       10217
#define IDS_ERR_FAILEDTOCREATECATEGORYTREE 10218
#define IDS_ERR_FAILEDTOCREATEHIERARCHYTREE 10219
#define IDS_ERR_FAILEDTOCONVERT         10220
#define IDS_ERR_FAILEDTOSETTOOLCATEGORY 10221
#define IDS_ERR_FAILEDTOLOADDEFAULTLIBRARY 10222
#define IDS_ERR_FAILEDTOINSERTTOOL      10223
#define IDS_ERR_FAILEDTOLOADPICTURE     10224
#define IDS_ERR_COULDNOTEMPTYCLIPBROAD  10225
#define IDS_ERR_COULDNOTALLOCATEMEMORY  10226
#define IDS_ERR_COULDNOTLOCKMEMORY      10227
#define IDCC_MARKER                     25175
#define IDCC_HAIR                       26308
#define IDCC_PIPET                      26311
#define IDCC_BUCKET                     26312
#define IDCC_PEN                        26313
#define IDCC_SIZEWIN                    26919
#define IDCC_SPRAY                      26923
#define IDCC_DRAGTOOL                   26924
#define IDC_HSPLITBAR                   30981
#define ID_VIEW_CATEGORIES              40001
#define ID_CATEGORY_DELETE              40002
#define ID_PAINT_LASSO                  40003
#define ID_CATEGORY_NEW                 40003
#define ID_PAINT_PEN                    40004
#define ID_PAINT_PATTERN                40005
#define ID_PAINT_FILL                   40006
#define ID_PAINT_LINE                   40007
#define ID_HIERARCHY                    40008
#define ID_PAINT_RECT0                  40009
#define ID_PAINT_RECT1                  40010
#define ID_PAINT_RECT2                  40011
#define ID_PAINT_CIRC0                  40012
#define ID_PAINT_CIRC1                  40013
#define ID_PAINT_CIRC2                  40014
#define ID_OPTIONS                      40016
#define ID_REPORT                       40017
#define ID_HEADER                       40018
#define ID_LIBRARY                      40019
#define ID_SNAPSHOT                     40020
#define ID_NORMAL_IMAGE                 40021
#define ID_PRESSED_IMAGE                40022
#define ID_HOVER_IMAGE                  40023
#define ID_DISABLED_IMAGE               40024
#define ID_SHIFT_LEFT                   40025
#define ID_SHIFT_UP                     40026
#define ID_INSERTBAND_STATUSBAR         40027
#define ID_INSERTBAND_POPUP             40028
#define ID_SHIFT_DOWN                   40029
#define ID_PAINT_PIPET                  40030
#define ID_APPLYALLTOOL                 40031
#define ID_STATICWIDTH                  40032
#define ID_FILEOPEN                     40033
#define ID_FILESAVE                     40034
#define ID_STATICHEIGHT                 40035
#define ID_HEIGHT                       40036
#define ID_WIDTH                        40037
#define ID_WIDTHSPIN                    40038
#define ID_SHIFT_RIGHT                  40039
#define ID_INSERTBAND_MENU              40040
#define ID_HEIGHTSPIN                   40041
#define ID_CUT                          40042
#define ID_COPY                         40043
#define ID_PASTE                        40044
#define ID_HELP_CONTENTS                40045
#define ID_UNDO                         40046
#define ID_CLEAR                        40047
#define ID_ACTIVEBARIMAGE               40050
#define ID_TOOLIMAGE                    40053
#define ID_CREATECHILDBAND              40055
#define ID_DELETEBAND                   40056
#define ID_HELP_ABOUT                   40057
#define ID_INSERTBAND_NORMAL            40058
#define ID_DELETETOOL                   40061
#define ID_CHILDBANDSIMAGE              40063
#define ID_CHILDBANDIMAGE               40064
#define ID_DELETECHILDBAND              40067
#define ID_FILE_LOAD                    40069
#define ID_INSERT_BAND_STATUSBAR        40070
#define ID_CANCEL                       40071
#define ID_TOOL                         40081
#define ID_INSERTTOOL_BUTTON            40082
#define ID_INSERTTOOL_DROPDOWNBUTTON    40083
#define ID_INSERTTOOL_TEXTBOX           40084
#define ID_INSERTTOOL_COMBOBOX          40085
#define ID_INSERTTOOL_LABEL             40086
#define ID_INSERTTOOL_SEPARATOR         40087
#define ID_TOOLDIALOG                   40089
#define ID_BUTTON40092                  40092
#define ID_BUTTON40093                  40093
#define ID_BUTTON40094                  40094
#define ID_BUTTON40095                  40095
#define ID_BUTTON40096                  40096
#define ID_BUTTON40097                  40097
#define ID_BUTTON40098                  40098
#define ID_TREEVIEWPAGE_INSERTTOOL_ACTIVEXCONTROL 40099
#define ID_TREEVIEWPAGE_INSERTTOOL_ACTIVEXFORM 40100
#define ID_BUTTON40073                  40101
#define ID_INSERTTOOL_ACTIVEXCONTROL    40102
#define ID_INSERTTOOL_ACTIVEXFORM       40103
#define ID_MENUGRAB                     40104
#define ID_INSERTBAND_CHILDMENU         40105
#define IDS_ACTIVEBARTREE               40105
#define ID_FILEEXIT                     40106
#define IDS_PROPERTYBROWSER             40106
#define IDS_ERR_VERSIONNUMBER           40107
#define IDS_COMMITCHANGES               40108
#define ID_VIEW_ACTIVEBAROBJECTS        40108
#define ID_VIEW_PROPERTYBROWSER         40109
#define ID_WINDOW_TILEHORIZONTAL        40111
#define ID_WINDOW_TILEVERTICALLY        40112
#define ID_WINDOW_CASCADE2              40113
#define ID_EDITBITMAP                   40117
#define ID_INSERTTOOL_WINDOWLIST        40118
#define ID_BUTTON40119                  40119
#define ID_FILE_SAVEAS                  40120
#define ID_FILENEW                      40122
#define ID_GEN_SELECT                   40123
#define ID_BUTTON40074                  40124
#define ID_BUTTON40075                  40125
#define ID_BUTTON40022                  40126
#define ID_BUTTON40013                  40127
#define ID_VERIFYIMAGEREFERENCECOUNT    40128
#define IDS_LAYOUTTYPE                  57604
#define IDS_LAYOUTFILETYPE              57605
#define IDS_SAVELAYOUT                  57606
#define IDS_OPENLAYOUT                  57610
#define IDS_RESTOREFILE                 57612
#define IDS_BACKUPFILE                  57613
#define IDS_NEW_TOOL                    57614
#define IDS_REPORT                      57615
#define IDS_HEADERFILE                  57616
#define IDS_TRUE                        57617
#define IDS_FALSE                       57618
#define IDS_PICNONE                     57619
#define IDS_NONE                        57619
#define IDS_PICBITMAP                   57620
#define IDS_BITMAP                      57620
#define IDS_PICICON                     57621
#define IDS_ICON                        57621
#define IDS_PICMETAFILE                 57622
#define IDS_METAFILE                    57622
#define IDS_PICENHMETAFILE              57623
#define IDS_ENHMETAFILE                 57623
#define IDS_SCROLLBAR                   57624
#define IDS_DESKTOP                     57626
#define IDS_ACTIVECAPTION               57627
#define IDS_INACTIVECAPTION             57628
#define IDS_MENU                        57629
#define IDS_WINDOW                      57630
#define IDS_WINDOWFRAME                 57631
#define IDS_MENUTEXT                    57632
#define IDS_WINDOWTEXT                  57633
#define IDS_CAPTIONTEXT                 57634
#define IDS_ACTIVEBORDER                57635
#define IDS_INACTIVEBORDER              57636
#define IDS_APPWORKSPACE                57637
#define IDS_HIGHLIGHT                   57638
#define IDS_HIGHLIGHTTEXT               57639
#define IDS_BTNFACE                     57640
#define IDS_BTNSHADOW                   57641
#define IDS_3DHIGHLIGHT                 57642
#define IDS_GRAYTEXT                    57643
#define IDS_BTNTEXT                     57644
#define IDS_INACTIVECAPTIONTEXT         57645
#define IDS_BTNHIGHLIGHT                57646
#define IDS_3DDKSHADOW                  57647
#define IDS_3DLIGHT                     57648
#define IDS_INFOTEXT                    57649
#define IDS_INFOBK                      57650
#define IDS_SYSTEM                      57653
#define IDS_PALETTE                     57654
#define IDS_BANDNAME                    57655
#define IDS_TOOLNAME                    57656
#define IDS_PAGENAME                    57657
#define IDS_CHILDBANDNAME               57657
#define IDS_CATEGORIES                  57658
#define IDS_DOCKLEFT                    57659
#define IDS_DOCKTOP                     57660
#define IDS_DOCKRIGHT                   57661
#define IDS_DOCKBUTTOM                  57662
#define IDS_FLOAT                       57663
#define IDS_CUSTOMIZE                   57664
#define IDS_HIDE                        57665
#define IDS_DETACH                      57666
#define IDS_FIXED                       57667
#define IDS_STRETCH                     57668
#define IDS_CENTERPOPUP                 57669
#define IDS_FAILEDTOSETPROPERTY         57670
#define IDS_NAME                        57671
#define IDS_CAPTION                     57672
#define IDS_BANDLIMIT                   57673
#define IDS_PAGES                       57674
#define IDS_CHILDBANDS                  57674
#define IDS_LIST                        57675
#define IDS_SHORTCUT                    57676
#define IDS_COMBOLIST                   57678
#define IDS_SETIMAGE                    57679
#define IDS_SETMASKIMAGE                57680
#define IDS_ACTIVEBAR                   57681
#define IDS_ICONEDITOR                  57682
#define IDS_SAVELAYOUTTYPE              57685
#define IDS_CATEGORYCREATE              57686
#define IDS_LOADPICTURETYPES            57687
#define IDS_SAVEPICTURETYPES            57688
#define IDS_BITMAPS                     57689
#define IDS_AUTOCREATEMASK              57690
#define IDS_CHOOSELIBRARY               57691
#define IDS_SORTBANDS                   57692
#define IDS_ERR_FAILEDTOCREATESHORTCUTOBJECT 57693

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40129
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
