//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by prj.rc
//
#define IDB_DYNABAR                     1
#define IDB_CUSTLISTBOX                 2
#define IDB_OVERFLOW                    10
#define IDB_CHECKLISTBOX_95             11
#define IDB_SMCOMBO                     12
#define IDB_MENUCHECK                   13
#define IDB_SYSRESTORE                  14
#define IDB_SYSMINIMIZE                 15
#define IDB_SYSCLOSE                    16
#define IDB_SYSMAX                      17
#define IDB_GRAB1                       18
#define IDB_GRAB2                       19
#define IDB_GRAB3                       20
#define IDB_GRAB4                       21
#define IDB_SYSSIZE                     22
#define IDB_SLIBINGSCROLL               23
#define IDB_CUSTOMIZELISTBOX            24
#define IDB_CASCADE                     25
#define IDB_TITEHORZ                    26
#define IDB_TITEVERT                    27
#define IDB_SUBMENUBMP                  28
#define IDB_MENUSCROLL                  29
#define IDCC_DRAGTOOLNOT                50
#define IDCC_DRAGTOOLMOVE               51
#define IDCC_DRAGTOOLCOPY               52
#define IDI_CONTROL                     60
#define IDI_DEFICON                     61
#define IDI_MENUMERGE                   62
#define IDD_ABOUT                       100
#define IDD_CUSTOMIZE                   101
#define IDD_NEWTOOLBAR                  102
#define IDD_ERROR                       103
#define IDD_CONFIRM                     104
#define IDD_TOOLBAR                     105
#define IDD_COMMANDS                    106
#define IDD_OPTIONS                     107
#define IDD_KEYBOARD                    108
#define IDD_DESIGNER                    109
#define IDD_DEMOSCR                     110
#define IDD_NEWCATEGORY                 111
#define IDI_DOCKABLE                    164
#define IDD_DOCKBAND                    166
#define IDC_VSPLITBAR                   167
#define IDR_MENUBAND                    172
#define IDB_EXPANDVERT                  173
#define IDB_EXPANDHORZ                  174
#define IDB_MENUEXPAND                  188
#define IDC_POINT                       195
#define IDB_XPMDIBUTTONS                203
#define IDC_EDIT1                       1000
#define IDS_VERB_DESIGNER               1000
#define IDS_NEWBUTTON                   1000
#define IDS_VERB_STANDALONE             1001
#define IDC_NEWTOOLBAR                  1002
#define IDC_RENAMETOOLBAR               1003
#define IDC_DELETETOOLBAR               1004
#define IDC_RESETTOOLBAR                1005
#define IDC_CATLIST                     1006
#define IDC_CATLISTSTATIC               1008
#define IDC_DESCSTATIC                  1009
#define IDC_DESCRIPTION                 1010
#define IDC_NAME                        1012
#define IDC_COMMANDSTATIC               1013
#define IDC_COMMANDS                    1014
#define IDC_NAMESTATIC                  1015
#define IDC_WEBADDRESS                  1016
#define IDC_ABICON                      1018
#define IDC_VERSION                     1019
#define IDC_NEW                         1020
#define IDC_RENAME                      1021
#define IDC_DELETE                      1022
#define IDC_RESET                       1023
#define IDC_CB_MENUANIMATION            1024
#define IDC_LT_CATEGORY                 1025
#define IDC_LT_COMMANDS                 1026
#define IDC_LB_KEYS                     1027
#define IDC_CLOSE                       1028
#define IDC_ASSIGN                      1029
#define IDC_REMOVE                      1030
#define IDC_RESETALL                    1031
#define IDC_ED_SHORTCUT                 1032
#define IDC_STATICTREE                  1034
#define IDC_LST_PROPERTIES              1037
#define IDC_LST_BAND                    1038
#define IDC_STATIC_MENU                 1039
#define IDC_STATIC_CATE                 1040
#define IDC_STATIC_CMD                  1041
#define IDC_STATIC_NEWSHORTCUT          1042
#define IDC_STATIC_CURRENTKEY           1043
#define IDC_STATIC_DESC                 1044
#define IDC_ST_CATEGORIES               1046
#define IDC_ST_COMMANDS                 1047
#define IDC_ST_DESC                     1049
#define IDC_LABEL_DESC                  1050
#define IDC_BN_MENUUSAGE                1051
#define IDC_ST_OTHER                    1053
#define IDC_CUSTOM1                     1054
#define IDC_CUSTOM2                     1055
#define IDC_MODSELECT                   1056
#define IDC_DONTSHOW                    1057
#define IDC_MSG                         1059
#define IDC_CK_MRUFIRST                 1060
#define IDC_CK_LARGE                    1061
#define IDC_CK_SCREENTIP                1062
#define IDC_CK_SHORTCUT                 1063
#define IDC_CK_FULLMENUAFTERDELAY       1064
#define IDS_CONTEXTCUSTOMIZE            2000
#define ID_VERB_DESIGNER                2000
#define IDS_CUSTTABS_TOOLBARS           2001
#define ID_VERB_STANDALONE              2001
#define IDS_CUSTTABS_COMMANDS           2002
#define IDS_CUSTOM_TOOLBARNAME          2003
#define IDS_NEWTOOLBAR                  2004
#define IDS_RENAMETOOLBAR               2005
#define IDS_TOOLBARNAMEEXISTS           2006
#define IDS_DELETETOOLBAR               2007
#define IDS_DELETETOOLBARTITLE          2008
#define IDS_CAT_NONE                    2009
#define IDS_ALT                         2010
#define IDS_CONTROL                     2011
#define IDS_SHIFT                       2012
#define IDS_NEW_TOOL                    2013
#define IDS_BANDFLAGS0                  2014
#define IDS_STRING2015                  2015
#define IDS_STRING2016                  2016
#define IDS_STRING2017                  2017
#define IDS_STRING2018                  2018
#define IDS_STRING2019                  2019
#define IDS_STRING2020                  2020
#define IDS_STRING2021                  2021
#define IDS_STRING2022                  2022
#define IDS_STRING2023                  2023
#define IDS_STRING2024                  2024
#define IDS_STRING2025                  2025
#define IDS_STRING2026                  2026
#define IDS_STRING2027                  2027
#define IDS_STRING2028                  2028
#define IDS_ERR_UNKNOWN                 3000
#define IDS_ERR_CANNOTCREATEFILE        3001
#define IDS_ERR_CANNOTOPENFILE          3002
#define IDS_ERR_INVALIDFILEFORMAT       3003
#define IDS_ERR_BANDNOTFOUND            3004
#define IDS_ERR_CYCLICPOPUP             3005
#define IDS_ERR_OPENINVALIDPOPUP        3006
#define IDS_ERR_BADTOOLSINDEX           3007
#define IDS_ERR_BADBANDSINDEX           3008
#define IDS_ERR_BADCOLLINDEX            3009
#define IDS_ERR_IMAGEBITMAPNOTSET       3010
#define IDS_ERR_MASKINVALIDSIZE         3011
#define IDS_ERR_COULDNOTCREATEDESIGNER  3012
#define IDS_ERR_QUERYACTIVEBARINTERFACE 3013
#define IDS_ERR_DUPLICATEBANDNAME       3014
#define IDS_ERR_DUPLICATETOOLID         3015
#define IDS_ERR_LAYOUT                  3016
#define IDS_ERR_BANDLIMIT               3017
#define IDS_ERR_INVALIDPROPERTYVALUE    3018
#define IDS_ERR_INVALIDPICTURE          3019
#define IDS_FAILEDTORESTORELAYOUT       3020
#define IDS_ERR_FAILEDTOGETWINDOWHANDLE 3020
#define IDS_ERR_INPROPERBORDERSTYLE     3021
#define IDS_ERR_MUSTBEARRAYOFSTRINGS    3022
#define IDS_ERR_WRONGTOOLTYPE           3023
#define IDS_ERR_INVALIDSHORTCUT         3024
#define IDS_ERR_DESIGNERFAILEDTOOPEN    3025
#define IDS_ERR_WINDOWISNOTVALID        3026
#define IDS_ERR_INVALIDPICTURETYPE      3027
#define IDS_ERR_ONLYONETOOLCANHAVEAUTOSIZE 3028
#define IDS_ERR_SIZERFLAGMUSTBESET      3029
#define IDS_ERR_ONLYFORUSEWITHSDIAPPLICATIONS 3030
#define IDS_ERR_NOTONSTATUSBAND         3031
#define IDS_ERR_CHILDBANDSHAVETOBENORMAL 3032
#define IDS_ERR_OUTOFMEMORY             3033
#define IDS_ERR_NULLNAMENOTALLOWED      3034
#define IDS_ERR_COMBOBOXISREADONLY      3035
#define IDS_SYSRESTORE                  4000
#define IDS_SYSMOVE                     4001
#define IDS_SYSSIZE                     4002
#define IDS_SYSMIN                      4003
#define IDS_SYSMAX                      4004
#define IDS_SYSCLOSE                    4005
#define IDS_SYSNEXT                     4006
#define IDS_MINIMIZEWINDOW              4008
#define IDS_RESTOREWINDOW               4009
#define IDS_CLOSEWINDOW                 4010
#define IDS_TOOLBAR                     4011
#define IDS_COMMANDS                    4012
#define IDS_OPTIONS                     4013
#define IDS_CUSTOMIZE                   4014
#define IDS_KEYBOARD                    4015
#define IDS_CLOSEBUTTON                 4016
#define IDS_ACTIVEBAR                   4017
#define IDS_REPORTEXCEPTION             4018
#define IDS_MENUOPTIONS                 4019
#define IDS_MENUOPTIONS2                4020
#define IDS_MENUOPTIONS3                4021
#define IDS_MENUOPTIONS4                4022
#define IDS_MENUOPTIONS5                4023
#define IDS_DESIGNER                    4024
#define IDS_DESIGNERDOC                 4025
#define IDS_HIERARCHY                   4026
#define IDS_CATEGORY                    4027
#define IDS_DESIGNERTITLE               4028
#define IDS_SYSCOMMAND                  4029
#define IDS_POPUPSYSCOMMAND             4030
#define IDS_MIWINDOW                    4031
#define IDS_WINDOW                      4032
#define IDS_POPUPWINDOW                 4033
#define IDS_MIMDIBUTTON                 4034
#define IDS_MICASCADE                   4035
#define IDS_CASCADE                     4036
#define IDS_MITILEHORZ                  4037
#define IDS_TILEHORZ                    4038
#define IDS_MITILEVERT                  4039
#define IDS_TILEVERT                    4040
#define IDS_MISEPARATOR                 4041
#define IDS_SEPARATOR                   4042
#define IDS_DOCKBAND                    4043
#define IDS_DOCKBANDDOC                 4044
#define IDS_ACTIVATE                    4045
#define IDS_TOOLNAME                    4046
#define IDS_STRING4047                  4047
#define IDS_TOOLRESET                   4047
#define IDS_TOOLDELETE                  4048
#define IDS_TOOLRESETCAPTION            4049
#define IDS_TOOLDELETECAPTION           4050
#define IDS_TOOLEDITNAME                4051
#define IDS_TOOLEDITNAMECAPTION         4052
#define IDS_TOOLCOPYIMAGE               4053
#define IDS_TOOLCOPYIMAGECAPTION        4054
#define IDS_TOOLPASTEIMAGE              4055
#define IDS_TOOLPASTEIMAGECAPTION       4056
#define IDS_TOOLDEFAULTSTYLE            4057
#define IDS_TOOLDEFAULTSTYLECAPTION     4058
#define IDS_TOOLTEXTONLY                4059
#define IDS_TOOLTEXTONLYCAPTION         4060
#define IDS_TOOLIMAGEONLY               4061
#define IDS_TOOLIMAGEONLYCAPTION        4062
#define IDS_TOOLIMAGEANDTEXT            4063
#define IDS_TOOLIMAGEANDTEXTCAPTION     4064
#define IDS_MORETOOLS                   4065
#define IDS_POPUPMORETOOLS              4066
#define IDS_POPUPALLTOOLS               4067
#define IDS_ALLTOOLSNAME                4068
#define IDS_ALLTOOLSCAPTION             4069
#define IDS_RESETTOOLBAR                4070
#define IDS_MOREBUTTONS                 4071
#define IDS_EXCEPTION_ACCESS_VIOLATION  5010
#define IDS_EXCEPTION_ARRAY_BOUNDS_EXCEEDED 5011
#define IDS_EXCEPTION_BREAKPOINT        5012
#define IDS_EXCEPTION_DATATYPE_MISALIGNMENT 5013
#define IDS_EXCEPTION_FLT_DENORMAL_OPERAND 5014
#define IDS_EXCEPTION_FLT_DIVIDE_BY_ZERO 5015
#define IDS_EXCEPTION_FLT_INEXACT_RESULT 5016
#define IDS_EXCEPTION_FLT_INVALID_OPERATION 5017
#define IDS_EXCEPTION_FLT_OVERFLOW      5018
#define IDS_EXCEPTION_FLT_STACK_CHECK   5019
#define IDS_EXCEPTION_FLT_UNDERFLOW     5020
#define IDS_EXCEPTION_ILLEGAL_INSTRUCTION 5021
#define IDS_EXCEPTION_IN_PAGE_ERROR     5022
#define IDS_EXCEPTION_INT_DIVIDE_BY_ZERO 5023
#define IDS_EXCEPTION_INT_OVERFLOW      5024
#define IDS_EXCEPTION_INVALID_DISPOSITION 5025
#define IDS_EXCEPTION_NONCONTINUABLE_EXCEPTION 5026
#define IDS_EXCEPTION_PRIV_INSTRUCTION  5027
#define IDS_EXCEPTION_SINGLE_STEP       5028
#define IDS_EXCEPTION_STACK_OVERFLOW    5029
#define IDS_BACKGROUNDOPTIONS           5030
#define IDS_STRING5031                  5031
#define IDS_STRING5032                  5032
#define IDS_STRING5033                  5033
#define IDS_RENAMECAPTION               5034
#define IDC_HSPLITBAR                   30981
#define IDC_COMBOSPLIT                  30982
#define ID_BUTTON40008                  40008
#define ID_BUTTON40014                  40014
#define ID_BUTTON40015                  40015
#define ID_BUTTON40016                  40016
#define ID_INSERTTOOL_WINDOWLIST        40044
#define ID_INSERTTOOL_BUTTON            40082
#define ID_INSERTTOOL_DROPDOWNBUTTON    40083
#define ID_INSERTTOOL_TEXTBOX           40084
#define ID_INSERTTOOL_COMBOBOX          40085
#define ID_INSERTTOOL_LABEL             40086
#define ID_INSERTTOOL_SEPARATOR         40087
#define ID_TREEVIEWPAGE_INSERTTOOL_ACTIVEXCONTROL 40099
#define ID_INSERTTOOL_ACTIVEXCONTROL    40099
#define ID_TREEVIEWPAGE_INSERTTOOL_ACTIVEXFORM 40100
#define ID_INSERTTOOL_ACTIVEXFORM       40100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
