#define csCtlActiveBar2	4
#define csMAboutActiveBar2	5
#define csPActiveBandActiveBar2	6
#define csPAlignToFormActiveBar2	7
#define csEBandCloseActiveBar2	9
#define csEBandDockActiveBar2	10
#define csEBandMoveActiveBar2	11
#define csEBandOpenActiveBar2	12
#define csEBandResizeActiveBar2	13
#define csPBandsActiveBar2	14
#define csEBandUndockActiveBar2	15
#define csEChildBandChangeActiveBar2	16
#define csPChildBandFontActiveBar2	17
#define csEClickActiveBar2	18
#define csEComboDropActiveBar2	19
#define csEComboSelChangeActiveBar2	20
#define csPControlFontActiveBar2	21
#define csMCustomizeActiveBar2	22
#define csECustomizeBeginActiveBar2	23
#define csECustomizeEndActiveBar2	24
#define csPDataPathActiveBar2	25
#define csEDataReadyActiveBar2	26
#define csPDisplayKeysInToolTipActiveBar2	27
#define csPDisplayToolTipsActiveBar2	28
#define csEErrorActiveBar2	29
#define csEFileDropActiveBar2	30
#define csPHighLightColorActiveBar2	31
#define csPLargeIconsActiveBar2	32
#define csMLoadActiveBar2	33
#define csMLoadLayoutChangesActiveBar2	34
#define csMLocalizeActiveBar2	35
#define csPMenuAnimationActiveBar2	36
#define csPMenuFontStyleActiveBar2	37
#define csEMenuItemEnterActiveBar2	38
#define csEMenuItemExitActiveBar2	39
#define csEMouseEnterActiveBar2	40
#define csEMouseExitActiveBar2	41
#define csENewToolbarActiveBar2	42
#define csMOnSysColorChangedActiveBar2	43
#define csMPlaySoundActiveBar2	44
#define csMRecalcLayoutActiveBar2	45
#define csMRefreshActiveBar2	46
#define csMRegisterChildMenuActiveBar2	47
#define csMReleaseFocusActiveBar2	48
#define csEResetActiveBar2	49
#define csEResizeActiveBar2	50
#define csMSaveActiveBar2	51
#define csMSaveLayoutChangesActiveBar2	52
#define csPShadowColorActiveBar2	53
#define csETextChangeActiveBar2	54
#define csEToolGotFocusActiveBar2	55
#define csEToolLostFocusActiveBar2	56
#define csEToolResetActiveBar2	57
#define csPToolsActiveBar2	58
#define csPVersionActiveBar2	59
#define csEWhatsThisHelpActiveBar2	60
#define csPWhatsThisHelpModeActiveBar2	61
#define csCtlBand	62
#define csPAutoSizeFormsBand	63
#define csPChildBandsBand	64
#define csPChildBandStyleBand	65
#define csPCreatedByBand	66
#define csPDockedHorzHeightBand	67
#define csPDockedHorzWidthBand	68
#define csPDockedVertHeightBand	69
#define csPDockedVertWidthBand	70
#define csPDockingAreaBand	71
#define csPDockingOffsetBand	72
#define csPDockLineBand	73
#define csPFlagsBand	74
#define csPGrabHandleStyleBand	75
#define csPHeightBand	76
#define csPLeftBand	77
#define csPMouseTrackingBand	78
#define csPNameBand	79
#define csMRefreshBand	80
#define csPTagVariantBand	81
#define csPToolsBand	82
#define csPToolsHPaddingBand	83
#define csPToolsHSpacingBand	84
#define csPToolsVPaddingBand	85
#define csPToolsVSpacingBand	86
#define csPTopBand	87
#define csPTypeBand	88
#define csPVisibleBand	89
#define csPWidthBand	90
#define csPWrapToolsBand	91
#define csCtlTool	92
#define csPAlignmentTool	93
#define csPAutoRepeatTool	94
#define csPAutoRepeatIntervalTool	95
#define csPCaptionPositionTool	96
#define csPCategoryTool	97
#define csMCBAddItemTool	98
#define csMCBClearTool	99
#define csPCBListTool	100
#define csPCBListCountTool	101
#define csPCBListIndexTool	102
#define csMCBRemoveItemTool	103
#define csPCBStyleTool	104
#define csPCBWidthTool	105
#define csPCheckedTool	106
#define csPControlTypeTool	107
#define csPCustomTool	108
#define csPDefaultTool	109
#define csPDescriptionTool	110
#define csMGetPictureTool	111
#define csPHeightTool	112
#define csPHelpContextIDTool	113
#define csPIDTool	114
#define csPLabelStyleTool	115
#define csPListTool	116
#define csPNameTool	117
#define csMSetFocusTool	118
#define csMSetPictureTool	119
#define csMSetPictureMaskTool	120
#define csPShortCutsTool	121
#define csPStyleTool	122
#define csPSubBandTool	123
#define csPTagVariantTool	124
#define csPTextTool	125
#define csPTooltipTextTool	126
#define csPVisibleTool	127
#define csPWidthTool	128
#define csCtlBands	129
#define csMAddBands	130
#define csMCountBands	131
#define csMItemBands	132
#define csMRemoveBands	133
#define csMRemoveAllBands	134
#define csCtlTools	135
#define csMAddTools	136
#define csMCountTools	137
#define csMInsertTools	138
#define csMItemTools	139
#define csMRemoveTools	140
#define csMRemoveAllTools	141
#define csCtlChildBands	142
#define csMAddChildBands	143
#define csPBackColorChildBands	144
#define csPChildBandBackgroundStyleChildBands	145
#define csPChildBandCaptionAlignmentChildBands	146
#define csPChildBandFont3DChildBands	147
#define csMCountChildBands	148
#define csPForeColorChildBands	149
#define csPHighLightColorChildBands	150
#define csMItemChildBands	151
#define csPPictureBackgroundChildBands	152
#define csPPictureBackgroundMaskColorChildBands	153
#define csPPictureBackgroundStyleChildBands	154
#define csPPictureBackgroundUseMaskChildBands	155
#define csMRemoveChildBands	156
#define csPShadowColorChildBands	157
#define csPToolForeColorChildBands	158
#define csCtlComboList	159
#define csMAddItemComboList	160
#define csMClearComboList	161
#define csMCountComboList	162
#define csMInsertItemComboList	163
#define csMItemComboList	164
#define csPItemDataComboList	165
#define csMRemoveComboList	166
#define csCtlCustomizeListbox	167
#define csPActiveBarCustomizeListbox	168
#define csMAddCustomizeListbox	169
#define csPCategoryCustomizeListbox	170
#define csMDeleteCustomizeListbox	171
#define csEErrorCustomizeListbox	172
#define csMRenameCustomizeListbox	173
#define csMResetCustomizeListbox	174
#define csESelChangeBandCustomizeListbox	175
#define csESelChangeCategoryCustomizeListbox	176
#define csESelChangeToolCustomizeListbox	177
#define csPTypeCustomizeListbox	179
#define csSetCaptionAlignmentTypes	180
#define csSetBandFlags	181
#define csSetTrackingStyles	182
#define csSetBandTypes	183
#define csSetCaptionPositionTypes	184
#define csSetToolTypes	185
#define csSetToolAlignmentTypes	186
#define csSetChildBandStyles	187
#define csSetMenuFontStyles	188
#define csSetFont3DTypes	189
#define csSetPictureBackgroundStyle	190
#define csSetChildBandBackgroundStyle	191
#define csSetSoundTypes	192
#define csSetMenuStyles	193
#define csSetLabelStyles	194
#define csSetCustomizeListboxTypes	195
#define csSetCustomizeTypes	196
#define csSetComboStyles	197
#define csSetToolStyles	198
#define csSetSaveOptionTypes	199
#define csSetLocalizationTypes	200
#define csSetCreatedByTypes	201
#define csCstAddBandandTool	203
#define csCstAddTwoBands	204
#define csCstSaveLoadLayouttoByteArray	205
#define csPAutoSizeChildrenActiveBar2	206
#define csPAutoUpdateStatusBarActiveBar2	207
#define csPBackColorActiveBar2	208
#define csMClearMenuUsageDataActiveBar2	209
#define csPClientAreaControlActiveBar2	210
#define csECustomizeHelpActiveBar2	211
#define csPFontActiveBar2	212
#define csPForeColorActiveBar2	213
#define csEKeyDownActiveBar2	214
#define csEKeyUpActiveBar2	215
#define csMLoadMenuUsageDataActiveBar2	216
#define csEMouseDownActiveBar2	217
#define csEMouseMoveActiveBar2	218
#define csEMouseUpActiveBar2	219
#define csPPersonalizedMenusActiveBar2	220
#define csPPictureActiveBar2	221
#define csMSaveMenuUsageDataActiveBar2	222
#define csEToolClickActiveBar2	223
#define csEToolDblClickActiveBar2	224
#define csEToolKeyDownActiveBar2	225
#define csEToolKeyUpActiveBar2	226
#define csPActiveToolBand	227
#define csCaptionBand	228
#define csPDisplayMoreToolsButtonBand	229
#define csPPictureBand	230
#define csMPopupMenuBand	249
#define csMPopupMenuExBand	250
#define csPCaptionTool	274
#define csPCBItemDataTool	275
#define csPEnabledTool	276
#define csPhWndTool	277
#define csPLeftTool	281
#define csPMenuVisibilityTool	291
#define csPTopTool	292
#define csPCurrentChildBandChildBands	293
#define csSetAutoSizeChildrenTypes	294
#define csSetDockingAreaTypes	296
#define csSetGrabHandleStyles	297
#define csSetMenuVisibilityStyles	298
#define csPFireDblClickEventActivebar2	299
#define csECustomizeToolClickActiveBar2	300
#define csMGetBandFromPositionActiveBar2	302
#define csMGetToolFromPositionActiveBar2	303
#define csPThreeDDarkShadowActiveBar2	304
#define csPThreeDLightActiveBar2	305
#define csMGetToolIndexBand	306
#define csPImageHeightTool	307
#define csPImageWidthTool	308
#define csPLabelBevelTool	309
#define csSetLabelBevelStyles	310
#define csSetImageTypes	311
#define csSetPersonalizedMenu	312
#define csPUserDefinedCustomizationActivebar2	313
#define csExUserCustomization	314
#define csMApplyAllTool	315
#define csPDockedHorzMinWidthBand	316
#define csPDockedVertMinWidthBand	317
#define csPScrollingSpeedBand	318
#define csPBackgroundOptionActiveBar2	319
#define csEToolComboCloseActiveBar2	320
#define csEToolKeyPressActiveBar2	321
#define csPClientAreaHeightActiveBar2	322
#define csPClientAreaLeftActiveBar2	323
#define csPClientAreaTopActiveBar2	324
#define csPClientAreaWidthActiveBar2	325
#define csPAutoSizeTool	326
#define csPSelLengthTool	327
#define csPSelStartTool	328
#define csPGradientEndColorChildBands	329
#define csPPopupBannerBackgroundColorBand	237
#define csPPopupBannerBackgroundStyleBand	248
#define csSetPopupBannerBackgroundStyles	295
#define csSetBackgroundOptionsTypes	330
#define csSetBandPopupMenuStyles	331
#define csPCBNewIndexTool	332
#define csPNewIndexComboList	333
#define csMRemoveAllChildBands	334
#define csSetToolAutoSizeTypes	335
#define csPClientAreaHWndActiveBar2	336
#define csPCBLinesTool	178
#define csEQueryUnloadActiveBar2	202
