#define HX_Features	231
#define HX_ActiveBar_Terms	232
#define HX_Architecture	233
#define HX_Installation	234
#define HX_System_Requirements	235
#define HX_Included_Files	236
#define HX_Using_ActiveBar	238
#define HX_Adding_ActiveBar_to_a_New_VB_Project	239
#define HX_ActiveBar_Designer	240
#define HX_Designer_Window	241
#define HX_Designer_Toolbar	242
#define HX_Tools_and_Bands_Treeview	243
#define HX_Context_Menus_2	244
#define HX_Keyboard_Shortcuts	245
#define HX_Properties_List	246
#define HX_Icon_Editor	247
#define HX_Menu_Capture	251
#define HX_Saving_ActiveBar_Layouts	252
#define HX_Layout_Documentation	253
#define HX_Tool_Libraries	254
#define HX_Designing_the_Layout	255
#define HX_Tool_Categories	256
#define HX_Bands	257
#define HX_Menu_Bars	258
#define HX_MDI_Child_Menus	259
#define HX_Toolbars	260
#define HX_Context_Menus_1	261
#define HX_Status_Bar_1	262
#define HX_Child_Bands	263
#define HX_Simple_User_Interface	264
#define HX_Action_Tools	265
#define HX_Setting_Shortcut_Keys	266
#define HX_Menu_and_Submenu_Bands	267
#define HX_Separators	268
#define HX_Toolbar_Bands	269
#define HX_Status_Bar	270
#define HX_Exploring_the_Active_Designer	271
#define HX_Finishing_up_the_Form	272
#define HX_Handling_Tool_Actions	273
#define HX_Multiple_Document_Interface_MDI_Forms	278
#define HX_MDI_Child_Window_List	279
#define HX_MDI_Child_Windows_Menu	280
#define HX_Advanced_User_Interface	282
#define HX_Tabbed_Bands_and_Shortcut_Bars	283
#define HX_Detachable_Menus	284
#define HX_Dockable_Forms	285
#define HX_ActiveX_Controls_as_Tools	286
#define HX_Runtime_Customization	287
#define HX_System_Menus	288
#define HX_Customization_Dialog	289
#define HX_Create_a_Customization_Dialog	290
#define HX_Packaging_and_Deployment	301
#define HX_Tools_Shared_Properties	352
#define HX_Creating_Context_Popup_Menus	2
#define HX_Office_2000_Features	3
